/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Uso Exclusivo
 */
public class Agenda extends javax.swing.JFrame {

    /**
     * Creates new form Agenda
     */
    public Agenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextFieldDATA = new javax.swing.JFormattedTextField();
        jButtonEmprestar = new javax.swing.JButton();
        jComboBoxNome = new javax.swing.JComboBox<>();
        jScrollPaneLivros = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jTextFieldDataDevolucao = new javax.swing.JTextField();
        jTextFieldRA = new javax.swing.JTextField();
        jLabelDataDevolucao = new javax.swing.JLabel();
        jLabelDataEmprestimo = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelEmprestimo = new javax.swing.JLabel();
        jLabelRA = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jFormattedTextFieldDATA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 230, 30));

        jButtonEmprestar.setBackground(new java.awt.Color(204, 204, 204));
        jButtonEmprestar.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jButtonEmprestar.setText("Emprestar");
        getContentPane().add(jButtonEmprestar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 380, -1, -1));

        jComboBoxNome.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", " " }));
        jComboBoxNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNomeActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 230, 30));

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Título", "Autor", "Área"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneLivros.setViewportView(jTable);

        getContentPane().add(jScrollPaneLivros, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 410, 240));
        getContentPane().add(jTextFieldDataDevolucao, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 230, 30));

        jTextFieldRA.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        jTextFieldRA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRAActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 230, 30));

        jLabelDataDevolucao.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabelDataDevolucao.setText("Data Devolução");
        getContentPane().add(jLabelDataDevolucao, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabelDataEmprestimo.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabelDataEmprestimo.setText("Data Empréstimo");
        getContentPane().add(jLabelDataEmprestimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabelNome.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabelNome.setText("Nome");
        getContentPane().add(jLabelNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabelEmprestimo.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jLabelEmprestimo.setText("EMPRÉSTIMO");
        getContentPane().add(jLabelEmprestimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        jLabelRA.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabelRA.setText("RA");
        getContentPane().add(jLabelRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));
        getContentPane().add(jLabelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 833, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldRAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRAActionPerformed

    private void jComboBoxNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEmprestar;
    private javax.swing.JComboBox<String> jComboBoxNome;
    private javax.swing.JFormattedTextField jFormattedTextFieldDATA;
    private javax.swing.JLabel jLabelDataDevolucao;
    private javax.swing.JLabel jLabelDataEmprestimo;
    private javax.swing.JLabel jLabelEmprestimo;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelRA;
    private javax.swing.JScrollPane jScrollPaneLivros;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTextFieldDataDevolucao;
    private javax.swing.JTextField jTextFieldRA;
    // End of variables declaration//GEN-END:variables
}
