/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Uso Exclusivo
 */
public class Aluno extends javax.swing.JFrame {

    /**
     * Creates new form Aluno
     */
    public Aluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCadastrarAluno = new javax.swing.JLabel();
        jLabelNomeAluno = new javax.swing.JLabel();
        jTextFieldNomeAluno = new javax.swing.JTextField();
        jLabelDataNasciemnto = new javax.swing.JLabel();
        jTextFieldDataNascimento = new javax.swing.JTextField();
        jLabelNumeroMatricula = new javax.swing.JLabel();
        jTextFieldNumeroMatrciula = new javax.swing.JTextField();
        jLabelCPF = new javax.swing.JLabel();
        jTextFieldCPF = new javax.swing.JTextField();
        jLabelEndereco = new javax.swing.JLabel();
        jTextFieldEndereco = new javax.swing.JTextField();
        jLabelCEP = new javax.swing.JLabel();
        jTextFieldCEP = new javax.swing.JTextField();
        jButtonCadastrarAluno = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCadastrarAluno.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabelCadastrarAluno.setText("Cadastrar Aluno");
        getContentPane().add(jLabelCadastrarAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jLabelNomeAluno.setText("Nome");
        getContentPane().add(jLabelNomeAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));
        getContentPane().add(jTextFieldNomeAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 150, 30));

        jLabelDataNasciemnto.setText("Data de nascimento");
        getContentPane().add(jLabelDataNasciemnto, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));
        getContentPane().add(jTextFieldDataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 150, 30));

        jLabelNumeroMatricula.setText("Número de matrícula");
        getContentPane().add(jLabelNumeroMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));
        getContentPane().add(jTextFieldNumeroMatrciula, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 150, 30));

        jLabelCPF.setText("CPF");
        getContentPane().add(jLabelCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));
        getContentPane().add(jTextFieldCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 150, 30));

        jLabelEndereco.setText("Endereço");
        getContentPane().add(jLabelEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));
        getContentPane().add(jTextFieldEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 370, 30));

        jLabelCEP.setText("CEP");
        getContentPane().add(jLabelCEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));
        getContentPane().add(jTextFieldCEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 150, 30));

        jButtonCadastrarAluno.setText("Cadastrar");
        getContentPane().add(jButtonCadastrarAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 120, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrarAluno;
    private javax.swing.JLabel jLabelCEP;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelCadastrarAluno;
    private javax.swing.JLabel jLabelDataNasciemnto;
    private javax.swing.JLabel jLabelEndereco;
    private javax.swing.JLabel jLabelNomeAluno;
    private javax.swing.JLabel jLabelNumeroMatricula;
    private javax.swing.JTextField jTextFieldCEP;
    private javax.swing.JTextField jTextFieldCPF;
    private javax.swing.JTextField jTextFieldDataNascimento;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldNomeAluno;
    private javax.swing.JTextField jTextFieldNumeroMatrciula;
    // End of variables declaration//GEN-END:variables
}
