/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Uso Exclusivo
 */
public class Livro extends javax.swing.JFrame {

    /**
     * Creates new form Livro
     */
    public Livro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jLabelCadastrarAluno = new javax.swing.JLabel();
        jTextFieldNomeLivro = new javax.swing.JTextField();
        jLabelISBN = new javax.swing.JLabel();
        jTextFieldISBN = new javax.swing.JTextField();
        jLabelNome = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldEdicao = new javax.swing.JTextField();
        jLabelAno = new javax.swing.JLabel();
        jTextFieldAno = new javax.swing.JTextField();
        jLabelCodigo = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jRadioButtonSim = new javax.swing.JRadioButton();
        jRadioButtonNao = new javax.swing.JRadioButton();
        jButtonCadastrarLivro = new javax.swing.JButton();

        jTextField2.setText("jTextField2");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCadastrarAluno.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabelCadastrarAluno.setText("Cadastrar Livro");
        getContentPane().add(jLabelCadastrarAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 180, 20));
        getContentPane().add(jTextFieldNomeLivro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 150, 30));

        jLabelISBN.setText("ISBN");
        getContentPane().add(jLabelISBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));
        getContentPane().add(jTextFieldISBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 150, 30));

        jLabelNome.setText("Nome");
        getContentPane().add(jLabelNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel2.setText("Edição");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));
        getContentPane().add(jTextFieldEdicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 150, 30));

        jLabelAno.setText("Ano");
        getContentPane().add(jLabelAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));
        getContentPane().add(jTextFieldAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 150, 30));

        jLabelCodigo.setText("Código");
        getContentPane().add(jLabelCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, -1));
        getContentPane().add(jTextFieldCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 150, 30));

        jLabel1.setText("Exemplar Biblioteca");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

        jRadioButtonSim.setText("Sim");
        getContentPane().add(jRadioButtonSim, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));

        jRadioButtonNao.setText("Não");
        getContentPane().add(jRadioButtonNao, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, -1, -1));

        jButtonCadastrarLivro.setText("Cadastrar");
        getContentPane().add(jButtonCadastrarLivro, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 110, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Livro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Livro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Livro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Livro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Livro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrarLivro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAno;
    private javax.swing.JLabel jLabelCadastrarAluno;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelISBN;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JRadioButton jRadioButtonNao;
    private javax.swing.JRadioButton jRadioButtonSim;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextFieldAno;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldEdicao;
    private javax.swing.JTextField jTextFieldISBN;
    private javax.swing.JTextField jTextFieldNomeLivro;
    // End of variables declaration//GEN-END:variables
}
