/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.MenuController;

/**
 *
 * @author Uso Exclusivo
 */
public class Menu extends javax.swing.JFrame {

    private final MenuController controller;
    /**
     * Creates new form menu_principal
     */
    public Menu() {
        initComponents();
        this.controller = new MenuController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFundo = new javax.swing.JLabel();
        jLabelIconLivro = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuAluno = new javax.swing.JMenuItem();
        jMenuLivro = new javax.swing.JMenuItem();
        jMenuEmprestar = new javax.swing.JMenu();
        jMenuAgenda = new javax.swing.JMenuItem();
        jMenuRelatorio = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelIconLivro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/open-book.png"))); // NOI18N
        getContentPane().add(jLabelIconLivro, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, -1, -1));

        jMenuCadastro.setText("Cadastrar");

        jMenuAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user.png"))); // NOI18N
        jMenuAluno.setText("Aluno");
        jMenuAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAlunoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuAluno);

        jMenuLivro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/two-books.png"))); // NOI18N
        jMenuLivro.setText("Livro");
        jMenuLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLivroActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuLivro);

        jMenuBar1.add(jMenuCadastro);

        jMenuEmprestar.setText("Emprestar");

        jMenuAgenda.setText("Agenda");
        jMenuAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAgendaActionPerformed(evt);
            }
        });
        jMenuEmprestar.add(jMenuAgenda);

        jMenuBar1.add(jMenuEmprestar);

        jMenuRelatorio.setText("Relatório");
        jMenuBar1.add(jMenuRelatorio);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAlunoActionPerformed
        // TODO add your handling code here:
        this.controller.irParaCadastrarAluno();
    }//GEN-LAST:event_jMenuAlunoActionPerformed

    private void jMenuAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAgendaActionPerformed
        // TODO add your handling code here:
        this.controller.irParaAgenda();
    }//GEN-LAST:event_jMenuAgendaActionPerformed

    private void jMenuLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLivroActionPerformed
        // TODO add your handling code here:
        this.controller.irParacadastrarLivro();
    }//GEN-LAST:event_jMenuLivroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelIconLivro;
    private javax.swing.JMenuItem jMenuAgenda;
    private javax.swing.JMenuItem jMenuAluno;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuEmprestar;
    private javax.swing.JMenuItem jMenuLivro;
    private javax.swing.JMenu jMenuRelatorio;
    // End of variables declaration//GEN-END:variables
}
